# GoldEdge Labs - Render Deployment Blueprint
# Maintainer: Joseph Were (Founder, GoldEdge Labs)
# Version: Ascension v5.1 - Stable Deployment

services:
  # --- Backend API ---
  - type: web
    name: goldedge-backend
    env: node
    plan: free
    autoDeploy: true
    region: oregon
    branch: main
    rootDir: 2_Backend             # ✅ tell Render where your backend code lives
    buildCommand: npm ci --omit=dev
    startCommand: node server.js
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: goldedge-mongo
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: goldedge-redis
          type: redis
          property: connectionString
      - key: NEUROEDGE_API_KEY
        sync: false
      - key: ADMIN_EMAIL
        value: josephogwe8@gmail.com
      - key: ADMIN_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://goldedge-labs.vercel.app

  # --- Redis Cache ---
  - type: redis
    name: goldedge-redis
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow backend connections

databases:
  # --- MongoDB Database ---
  - name: goldedge-mongo
    databaseName: goldedge_labs
    plan: free
    region: oregon